update_variables
MasterWork1995/JS-team-project-Filmoteka pull request #6
Opened 2021-07-24 19:35 UTC by TKatVol

2021-07-24 20:19 UTC, MasterWork1995 requested changes

2021-07-24 20:19 UTC, MasterWork1995 commented on src/sass/utils/_variables.scss
> +$accentColor: #ff6b08;
Кать, там більше кольорів є, футер ще має кольори. Дороби

2021-07-24 23:27 UTC, TKatVol commented on src/sass/utils/_variables.scss
> +$accentColor: #ff6b08;
Додала $textColorFooter

2021-07-25 05:40 UTC, TKatVol commented on src/sass/utils/_variables.scss
> +$accentColor: #ff6b08;
+ $backgroundColorFooter

2021-07-25 09:10 UTC, MasterWork1995 approved these changes

2021-07-25 09:10 UTC, merged